source 'https://rubygems.org'

gem 'rails', '~> 5.1.3'
gem 'slim-rails'
gem 'haml-rails'
# gem 'liquid-rails'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
